dist: bionic
branches:
  only:
    - master
before_script:
  - GAMA_URL=$(curl -s https://api.github.com/repos/gama-platform/gama/releases/tags/continuous | grep  continuous/GAMA1.8_Continuous_Linux | cut -d ':' -f 2,3 | tr -d \")
script:
  - curl -o gama.zip -fSL $GAMA_URL
  - unzip gama.zip -d ./GAMA
  - chmod +x ./GAMA/headless/gama-headless.sh
  - mkdir ./COMOKIT-HPC
  - mv ./pre-processing ./COMOKIT-HPC
  - mv ./post-processing ./COMOKIT-HPC
  
  - git clone https://github.com/COMOKIT/COMOKIT-Model.git ./Model
  - mv ./Model/COMOKIT ./COMOKIT-Model
after_success:
  - zip -r ./GAMA-COMOKIT-HPC.zip ./GAMA ./COMOKIT-Model ./COMOKIT-HPC


before_deploy:
  # Remove latest release
  - LATEST_COMOKIT_HPC_URL=$(node -pe 'JSON.parse(process.argv[1]).url' "$(curl -s  https://api.github.com/repos/COMOKIT/COMOKIT-HPC/releases/tags/latest)")
  - echo $LATEST_COMOKIT_HPC_URL
  - "curl -H \"Authorization: token ${GITHUB_API_KEY}\" -X DELETE ${LATEST_COMOKIT_HPC_URL}"
  # Update tag
  - git remote add master https://${GITHUB_API_KEY}@github.com/COMOKIT/COMOKIT-HPC.git
  - git fetch master --tags
  - git tag -f latest
  - git push master --tags -f
deploy:
  provider: releases
  name: "All-In-One Archive"
  body: "Prerelease of COMOKIT archived with GAMA Continuous, COMOKIT's default models and HPC scripts"
  overwrite: true
  tag_name: latest
  prerelease: true
  file: "./GAMA-COMOKIT-HPC.zip"
  skip_cleanup: true
  on:
    repo: COMOKIT/COMOKIT-HPC
    branch: master
    tags: false
  api_key: $GITHUB_API_KEY